modLoader="javafml"
loaderVersion="[32,)"
license="CoFH \"Don't Be a Jerk\" License"

[[mods]]
	modId="draconicevolution"
	displayName="Draconic Energy"
	version="${version}"
	authors="brandon3055"
	description='''Literally just Draconic Evolution but with the OP tools and armor gutted out.'''
[[dependencies.draconicevolution]]
	modId="forge"
	mandatory=true
	versionRange="[35.1,)"
	ordering="NONE"
	side="BOTH"
[[dependencies.draconicevolution]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.draconicevolution]]
    modId="computercraft"
    mandatory=false
    versionRange="[${cct_version},)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.draconicevolution]]
	modId="codechickenlib"
	mandatory=true
	versionRange="${ccl_version}"
	ordering="AFTER"
	side="BOTH"
[[dependencies.draconicevolution]]
	modId="brandonscore"
	mandatory=true
	versionRange="[${bcore_version},)"
	ordering="AFTER"
	side="BOTH"

